apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: monitoring-platform
data:
  NODE_ENV: "production"
  PORT: "4000"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "events_db"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
