apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: monitoring-platform
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres123"
  SENTRY_DSN: "https://your-key@sentry.io/your-project"
